---
title: "IRES Metrics: Duration"
author: "Tobias Gauster, Cath Sefton"
date: "February 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

This document was created with package version ``r packageVersion("smires")``. Currently the following datasets are already included in the package:
```{r initialisation, warning=FALSE, message=FALSE}
library(smires)
data(package = "smires")$results[, "Item"]
```


When calculating metrics regarding the duration of intermittency, a ternary time series (dry, wet, `NA`) can be derived.  The binary series is added as a column named `state`. 

```{r}
b <- dry_events(balder)
head(b)
```


# Metrics for grouped time series
```{r}
events <- balder %>% 
  dry_events() %>% 
  per(period = "year") %>% 
  duration()

print(events)
```


```{r, eval=FALSE}
events <- duration(per(dry_events(balder), period = "year"))
```


```{r}
plot_events(events)
```


```{r}
ggplot(events, aes(duration)) + geom_histogram(bins = 10) + 
  facet_wrap(~state) + 
  labs(x = "Duration of the state in days")

ggplot(events, aes(duration, col = state)) + stat_ecdf() + 
  labs(x = "Duration of the state in days", y = "Probability of non-Exceedance", 
       title = "Empirical Cumulative Distribution Function (ECDF)")
```


```{r}
bb <- events %>% group_by(period, state) %>% 
  summarise(duration = max(duration)) %>% 
  group_by(state) %>% summarise(mDur = mean(duration))

bb
```



```{r}
ggplot(events, aes(duration)) + geom_histogram(binwidth = 10) + 
  scale_x_continuous(limits = c(0, NA)) + 
  facet_grid(period~state) + 
  labs(x = "Duration of the state in days")
```